<div class="container">
                    <h2 class="title text-center custom mb25">Policy for Buyers</h2>
                    <div class="blog-row">
                   <div>
  <div>
    <p><strong>Capitalized terms used but not defined herein shall have the meaning given to them under the User Agreement.</strong></p>
    <ul>
      <li>As a buyer, you understand and  accept that upon initiating a   Transaction on the Website, you are entering into  a legally binding and   enforceable contract with the seller to purchase the  items from the   seller using either Payment on Billing or Payment on Delivery as  the   method of payment to pay the Transaction Price which shall be paid to   the  seller through your Issuing Bank (except in case of cash payments).   You agree  and acknowledge that the Company is only a facilitator of   collection and  remittance of Transaction Price. No interest or any   benefits whatsoever is  given to or can be claimed by the Buyer on the   Transaction Price collected by  the Company through and of the   prescribed payment methods.</li>
      <br>
      <li> You may agree with the seller  on the commercial terms of the   Transaction including terms of Dispatch and  Delivery time or any   extension thereof by way of exchange of electronic  records/ electronic   communication by using the features as may be provided on  the Website   and the Transaction shall stand amended to such extent, provided  that   any such variation of the terms of the Transaction are not in violation   of  the User Agreement and the rules and policies made there under. </li>
      <br>
      <li> <strong>Payment Method</strong>: You shall pay the  Transaction   Price through the available methods of payment i.e. Payment on  Billing   or Payment on Delivery, for the Transactions conducted on the Website.    You will be intimated when (i) the Transaction Price is credited to the   account  of the Company (in case of Payment on Billing) or (ii) on   committing to pay the  Transaction Price on Delivery if you opt for   Payment on Delivery payment  method, which will be confirmed by the   Website.  The Website shall notify the Buyer upon  Payment Confirmation   as provided herein.</li>
      <br>
      <li> <strong>Non-payment</strong>: Buyers are not permitted to  buy   any product without making a payment of the Transaction Price by Payment   on  Billing method of opting for Payment on Delivery or such other   payment method  provided by the Company on the Website, in respect of   the product as described  in the listing.</li>
      <br>
      <li> <strong>Contacting Users</strong>: Users shall not  communicate   with other Users outside the Website to warn them about a seller,    products or listing. However, you are entitled to provide feedback   and/or  reviews/ ratings for sellers as per the feedback facilities   provided on the  Website.</li>
      <br>
      <li> <strong>Contact Information</strong>: The contact details    provided by you on the Website shall be accurate and current at all   times and  you shall be obliged to update any change in your contact   information on the  Website immediately. The Company takes no   responsibility for any delay/ non  delivery of the goods on account of   failure of the User to update the contact  information provided on the   Website and any consequent negative feedback by the  buyer will be   deleted or modified.</li>
      <br>
      <li> <strong>Feedback</strong>: You shall use the feedback and  review   mechanism to communicate your fair opinion and facts in respect of any    User or the Website or your experience whilst using the Website, known   to you  from first-hand experience only. You shall not include any   hearsay information,  or information that results in maligning any User,   brand or product in your  feedback. You must inform the Company   immediately on becoming aware of  violation of any applicable laws or   violation of the provisions of this User  Agreement and the rules and   policies made thereunder at customercare@kesaron.com</li>
      <br>
      <li> <strong>Limit on volume of Transactions</strong>: The  Company   reserves the right to limit the amount payable and the volume of the    Transaction that may be conducted on a single Valid Card/ Valid Bank   Account by  a Buyer and may refuse to process Transactions exceeding   such limits and may  also block certain Valid Cards or Valid Bank   Accounts that are suspected to be  misused while paying the Transaction   Price.</li>
      <br>
      <li> <strong>Verification of payment</strong>: To prevent any  misuse,   a payment (in whichever method) of the Transaction Price initiated by    the Buyer may be flagged or kept on hold for additional checks and   verification  in which case the Company may contact the buyer for   verification of or  additional information, details, data and documents.   The Company may not  confirm the payment if such information, details,   data and documents are false,  misleading, incorrect or incomplete and   consequently the Valid Card and/or the  Valid Bank Account will not be   charged. In such case, the Dispatch timelines  will not commence until   Payment Confirmation. The result of the checks and  verification shall   be communicated to the buyer and seller. </li>
      <br>
      <li> The  Company reserves the right to refuse to process Transaction   Price in respect of  Transactions by Buyers with a prior history of   questionable charges including  without limitation breach of any   agreements by Buyer with the Company or  breach/ violation of any   applicable law or any charges imposed by the Issuing  Bank.</li>
      <br>
      <li> <strong>Payment Confirmation</strong>: In case of payment  by   Payment on Billing, upon successful receipt of the Transaction Price by   the Company  from the Buyer within [3] days of booking the Transaction   and completion of  verification of payment in accordance with the clause   above, the Company shall  notify the buyer and the seller that the   Transaction Price has been received.  In case of payment by Payment on   Delivery, the Company shall notify the buyer  and seller that the buyer   has committed to pay the Transaction Price by Payment  on Delivery.</li>
      <br>
      <li> <strong>Dispatch Details</strong>: The seller or the  Company (if   the seller is availing kesaron Logistics services) shall  provide   the Dispatch Details on the Website within [7] days from the Payment    Confirmation or within such timelines as may be agreed upon between the   buyer  and seller on the Website. If the Seller fails to enter the   Dispatch Details on  the Website within such prescribed time, the   Company may in its sole discretion  cancel the Transaction and refund   the Transaction Price (if paid) to the Buyer.  In case of Delivery   outside India (in which case only electronic payment shall  be   acceptable), the Dispatch Details have to be entered on the Website   within [5]  days of Payment Confirmation.</li>
      <br>
      <li> <strong>Delivery</strong>: The time within which the seller  or   the Company (if the seller is availing kesaron Logistics services)   is  required to ensure Delivery of the items to the buyer shall be   calculated from  the time the seller/Company enters the Dispatch Details   on the Website i.e.  within 7 days from entering the Dispatch Details   for delivery within India and  within 21 days from entering the Dispatch   Details for delivery outside India or  such other timeline as may have   been agreed upon between the buyer and seller and  intimated on the   Website. </li>
      <br>
      <li> <strong>Delivery confirmation</strong>: You shall  immediately   notify the Website upon Delivery or non Delivery within the  prescribed   time period. If you fail to provide such notification/ confirmation  of   receipt or non-receipt of an item within [7] days of expiry of the   Delivery  time prescribed in the above clause, it shall be construed as a   deemed Delivery  in respect of that Transaction and the Transaction   Price shall not be refunded.  In case of Cash on Delivery Transactions   or if the seller is availing  kesaron Logistics services, the   Company will update the shipment Delivery  status on a periodic basis   and the Buyer is not required to confirm receipt of  items.</li>
      <li><br>
        <p><strong>Refund:</strong> You shall be entitled to claim a refund   of the Transaction Price (as your sole and exclusive remedy) within [7]   days of expiry of the Delivery time (including any extension thereof) if   you do not receive the Delivery within the time period agreed in the   Transaction or within the time period prescribed herein, whichever is   earlier. In the event you do not raise a refund claim using the Website   within the prescribed time you shall be ineligible for a refund.</p>
        <br>
        <p>If you fail to receive an item shipped to you on account of   providing inadequate or inaccurate shipping address or your   non-availability at the address provided or failure to make requisite   payment at the time of delivery, the Transaction will be cancelled and   the item will be returned to the seller and the Company and the seller   will be entitled to recover reasonable compensation for services   provided and costs incurred for shipping, handling, couriering,   processing your order and any other services provided to you.</p>
        <p> In cases where the buyer has received Delivery of the item   within the stipulated time but the item is not as described in the   listing, the buyer is entitled to claim a refund for the entire   Transaction Price paid within [5] days from the expiry of the Delivery   time. If such refund claim is raised by the buyer, the seller has the   option to disagree to the same, in which case the Company may put the   refund claim on hold for checks and verifications. The Company may   contact the Users for the purposes of verification. As a result of such   verification, the refund claim may either be accepted or rejected by the   Company in its sole discretion which shall not be disputed by the   Users. If the refund claim is accepted then the Transaction Price will   be refunded to the buyer. </p>
        <br>
        <p> All payments for refund of the Transaction Price shall be as   follows and in accordance with the provisions contained herein and   applicable laws in India, particularly the directions issued by the   Reserve Bank of India from time to time for opening and operation of   accounts and settlement of payments for electronic payment transactions   involving intermediaries dated 24 November 2009.</p>
        <br>
        <ul>
          <li>Except for Payment on Delivery  Transaction, refund, if any,   shall be made at the same Issuing Bank from where  Transaction Price was   received. </li>
          <li> For Payment on Delivery  Transactions, refunds, if any, will   be made via demand draft in favour of the  Buyer (as per the details   provided by the Buyer at the time of registration  with the Website). </li>
          <li> Refunds shall only be made in  Indian Rupees and shall be   equivalent to the Transaction Price received. Buyer  shall bear any   foreign exchange conversion risk, loss, charges or fees, if any.</li>
          <li> For electronics payments,  refund shall be made through the   VillaPay Facility using NEFT / RTGS or any  other online banking /   electronic funds transfer system approved by Reserve  Bank India. </li>
          <li> Refund shall be subject to the buyer  complying with the   provisions of the User Agreement and the rules and polices  made   hereunder and the Company shall have recourse to such refund in case of    any misuse by buyer.</li>
        </ul>
      </li>
      <br>
      <li><strong>Arrangement with the Issuing Bank:</strong> All   Transactions conducted on the Website for which Valid Cards and Valid   Bank Accounts are used for remittance of payment for Transactions on the   VillaPay Facility will also be governed by the terms and conditions   agreed to between the buyer and the respective Issuing Bank and payment   instrument issuing company and you shall not violate any such terms and   conditions. You agree to indemnify and hold harmless the Company and its   service providers against any direct or indirect liability that may   arise on account of such violation. All online bank transfers from Valid   Bank Accounts are processed using the gateway provided by the   respective Issuing Bank which support the VillaPay Facility to provide   these services to the Users.</li>
      <br>
      <li><strong>Octroi and other local levies:</strong> Delivery of items   to buyers located in places where octroi or other local taxes and levies   are charged will be liable to pay the same to the courier company even   though the listing mentioned no such octroi, taxes or levy. </li>
    </ul>
  </div>
</div>
 
                    </div><!-- End .row -->
                </div>