<div class="container">
                    <h2 class="title text-center custom mb25">Seller Policy</h2>
                    <div class="blog-row">
                         <h2>Policy for Sellers</h2>
<div>
  <div>
  <p><strong>Capitalized terms used but not defined herein shall have the meaning  given to them under the User Agreement. </strong></p>
  <ul>
  <li> <strong>Seller Registration</strong>: A User who wishes  to sell items on the Website shall register with the KesaronPay Facility by  providing the requisite information/ data on the KesaronPay Seller  Registration page including details of the seller&rsquo;s Valid Bank Account (<strong>KesaronPay Seller Registration</strong>). The  sellers shall provide true, correct and duly authorized data/ information and  shall not be misleading, fraudulent, false, unauthorized and otherwise illegal.  The Company has the right to suspend/ terminate the KesaronPay Seller  Registration and the use of the Website by the seller if the Company discovers  or it is brought to the Company's notice that the aforesaid data is misleading  or does not comply with the User Agreement and the rules and polices made  thereunder and in such case the seller shall also be liable for all the  liabilities, risks, damages and consequences that may arise.</li>
  <li>
    <p><strong>Invoicing, Shipping &amp; Product Liabilities: </strong> Please note that we are a marketplace platform like Ebay and provide marketplace services to you. We help Buyers and Sellers connect whereby as Sellers you are selling to customers via our platform and we are charging commission for services associated with it. Therefore invoicing and shipping to customer is your responsibility. Also any taxation related to sale of your products like VAT, CST etc is your responsibility. Also liabilities arising from the use, consumption and/or interaction with your products is solely yours and Kesaron.com will not be responsible for any loss or damage due to your products.</p>
  </li>
  <li>
    <p><strong>Hold, Suspension and Termination of KesaronPay Seller Registration: </strong>In case of any breach or violation or suspected breach or violation  of any of the provisions of this policy or the User Agreement, the Company may  suspend and/or terminate the KesaronPay Seller Registration or may put the  remittances on hold with respect to such Seller. The Company may reinstate or  activate seller&rsquo;s KesaronPay Seller Registration or remit the Transaction Price  to seller subject to the Seller providing such information, data, documents and  undergoing such verification as may be desired by the Company and as provided  in the User Agreement or the rules and polices made thereunder. Seller&rsquo;s KesaronPay  Seller Registration is subject to the seller remaining an active User of the  Website.</p>
    <p> Upon identifying or being notified by any person or by law  enforcement agency that Seller has violated any law in the performance of the  Transaction, the Company may immediately suspend seller&rsquo;s KesaronPay Seller  Registration, notify law enforcement or any other authority including banks for  appropriate action or act in any other way to cooperate with authorities or  protect its interests.</p>
  </li>
  <li>
    <p><strong>Know Your Customer (KYC) Documentation: </strong>At  the time of KesaronPay Seller Registration and/or at any time thereafter and/or  from time to time as may be required, the Company may seek KYC Documents from  Seller and further usage of the Website shall be subject to Seller&rsquo;s submission  of KYC Documents. 'KYC Documents' shall mean such information, data or  documents as may be specified by the Company from time to time which clearly  and unambiguously verifies the details, including the Seller&rsquo;s Bank Account  provided by Seller at the time of registration with KesaronPay Facility or at any  subsequent date.</p>
    <p> The Company may seek KYC Documents from the Seller at any point of  time during the subsistence of this policy for compliance with the provisions  of the User Agreement and the rules and polices made thereunder as well as  compliance with applicable laws. The Company has the right to reject any one or  more of the KYC Documents submitted by seller and may ask for other documents  or further information.</p>
  </li>
  <li>
    <p><strong>Charges Applicable to Sellers</strong>: The  Company shall levy charges/ fees from time to time (for providing facilities to  sell on the Website) to the Sellers in accordance with the Facility Charges  Policy incorporated herein by reference. The Company will provide the  Seller with an invoice reflecting the facility charges on a monthly basis. If  the seller avails of any of the services provided under Kesaron Logistics  by the Company, the seller will be liable to pay additional fees, charges in  respect of the services availed as set out in the Facility Charges Policy.</p>
    <p> The Company reserves the right to change the Facility Charge Policy  and the related rules and policies from time to time. The Company may introduce  new services and modify some or all of the existing services offered on the  Website and/or under Kesaron Logistics. Any such changes shall be effective  from the time that the Company posts the same on the Website.</p>
    <p>The Seller will be responsible for paying all charges associated  with the use of the Website and/or Kesaron Logistics and agrees to bear any  and all applicable taxes, charges, cesses, surcharges etc. levied thereon. The seller  shall pay the remit the appropriate charges to the Company or the Company will  deduct such charges from the Transaction Price to be remitted to the seller.  The Company shall issue the invoice after such deduction and remittance. Unless  otherwise provided, the charges are payable by the Seller irrespective of any  charge back, refund or non-fulfilment of the Transaction.</p>
    <p>The Company reserves the right to set minimum and maximum  transaction limits on the Website as it may determine for the safety of its  Users.</p>
  </li>
  <li>
    <p><strong>Single Listing</strong>: You will only make one  listing for each single item that is offered for sale by you on the Website. If  you propose to sell more than one identical item you will make a separate  listing for each of them and if all listings result in successful sale you must  be in a position to fulfily all such orders. All listed items must be listed in  an appropriate category on the Website. Each listing must contain only one  specific item for sale and no choices whatsoever (such as colour, size etc.)  shall be provided to the buyer. [<strong><em>Note: Please confirm</em></strong>.]</p>
    <p> You agree not to  list and propose to sell any item on the Website that is set out in the list of  Restricted Items set out in <strong>Annex 1 </strong>hereto. </p>
    <p> All  listed items must be kept in stock for successful fulfilment of sales. No  listing can contain a disclaimer that suggests that a sale will be completed or  order will be confirmed only if the item is available with the User who is  listing the item. You agree that you shall not list an item if you are not in a  position to deliver it immediately. </p>
    <p> You  shall not make any listing in the nature of 'wanted advertisements' that do not  offer to sell an item but invites Users to make an offer to you for sale of any  item.</p>
    <p> You  will also not make any offer, either online or offline, or by making another  listing on a different website, to sell an item once you have made a listing  with respect to such an item on the Website. You will not make a listing on the  Website with respect to an item which is subject to an existing online or  offline offer which can be validly accepted, including listing on the Website  or other websites. In no circumstances will you attempt to divert any User  through your listing to any other webpage or provide him any information in  order to conduct any transaction outside of the Website. </p>
    <p> The  Company will be required to remove a listing only upon it being reported to be prohibited  or restricted (Annex 1) or violative of applicable law or terms of the User  Agreement. The Company is not deemed to have any knowledge of such prohibitive,  restricted or violative listing until it has been reported to the Company. Upon  receiving such reporting the Company will take best efforts to remove such  listing at its sole discretion (but will not be liable to do so), within 7 days  of receiving such reporting. </p>
  </li>
  <li> <strong>No Infringement of Intellectual Property of Company and Third Parties</strong>: You must ensure that the listed items do not infringe upon the  intellectual property, trade mark, copyright, trade secret or other proprietary  rights or rights of publicity or privacy rights of any third party. Listings  may only include content generated by you in the form of text descriptions,  graphics and pictures that describe your item for sale. You agree that use of  logos or trademark owned by a third party producer or manufacturer can lead to  infringement of intellectual property rights of such third party. You will be  solely responsible for listing and use of such trademark or intellectual  property on the Website, and will hold the Website and the Company indemnified  and harmless against any claim by third parties that may arise in respect of  such use. You agree that under no circumstances would you use brand names or  trademarks not owned by you unless the item that you are listing on the Website  carries the brand name or trademark of its original manufacturer or producer.  You further agree not to use any intellectual properties of the Website or the  Company including its trademarks, brand name in any manner whatsoever. You will  not represent to any User or third party, in any manner, that you are  affiliated or associated with the Website or the Company or that you have any  right to represent the Website or the Company. </li>
  <li>
    <p><strong>Appropriate Description in Listing:</strong> You  shall be responsible for providing information relating to the items offered to  be sold by you on the Website. You undertake that all such information at all  times shall be accurate and complete in all respects. The listing description  of the item must not be misleading in any manner whatsoever and must describe  the actual condition of the item. You shall not exaggerate or over emphasize  the attributes of any items you propose to sell on the Website so as to mislead  other Users in any manner. If the item description does not match the actual  condition of the item, you agree to refund any amounts that you may have  received from the buyer. You agree not to use misleading titles for listing and  not provide misleading or inadequate information about the location of any  listed item. If for any reason you are unable to deliver to any specific  location, destination or country, you must clearly mention the same on the  listing. You shall not use unrelated keywords, or brand names (even if such use  does not lead to any intellectual property right violation), or text unrelated  to the item on offer for sale in your listing. </p>
    <p> You  shall not provide any information such as a catalogue of your items in your  listing or on the items or packaging thereof which will enable a buyer to  contact you outside the Website to buy such item directly from you instead of  buying it from the listing on the Website. You shall not solicit Users to send  you payments by any method not approved or provided for on the Website by the  Company.</p>
    <p> Any image used in  the listing must be of the actual item proposed to be sold on the listing and  shall not copy images from other listings available on the Website. You cannot  disclaim any liability including liability with respect to authenticity,  merchantability of items that you offer to sell on the Website. </p>
    <p> You  shall not endorse any item other than that being listed by you anywhere in the  Website. You agree not to provide any description in any listing made by you in  any manner that suggests you are in any way connected to, or are representing  or selling on behalf of a manufacturer or producer of the item unless you are  the manufacturer or producer, or you have obtained a written permission or  entered into an agreement with such manufacturer or producer under which you  are entitled to represent as such. </p>
    <p> [Any free or bonus  item promised in a listing for promotional purposes must be delivered together  with the main item being offered through the listing. All provisions of the  User Agreement including the rules and policies made there under that apply to  the main item will apply mutatis mutandis to the free or bonus item as well to  the extent it may be applicable.] </p>
    <p> If you opt to avail  of the 'listing services' provided under Kesaron Logistics by the Company  you agree to comply with the terms and conditions of <strong>Policy of Kesaron  Logistics</strong> incorporated herein by reference. If you choose, Kesaron  Logistics will assist you in writing an appropriate description of an item to  be listed, taking photographs/images of the items to be uploaded on the Website  etc. In such case, you are liable to verify all such content of the listing,  photograph/ image etc. provided by Kesaron Logistics and edit/ modify/  vary/ delete as may be necessary to accurately describe the item to be listed.  It is clarified that the copyright in all photographs/ images produced with the  assistance of Kesaron Logistics shall exclusively belong to the Company.  You agree that under no circumstance will the Company be liable for any  misrepresentation in respect of the listed item.</p>
  </li>
  <li> <strong>Categories:</strong> If the Website provides for  categories of items, then the User must take adequate care to list items in the  appropriate category. Failure to do so may result is cancellation of listing. </li>
  <li> <strong>Method of Payment</strong>: At the time of  listing, of the various modes of payment provided by the Company on the  Website, you shall also choose the modes of payment which are acceptable to you  and the buyer will have the option to pay the Transaction Price only by the  modes of payment selected by you. If you fail to choose your preferred modes of  payment, the Buyer will have the option to pay the Transaction Price by any  mode of payment provided on the Website. </li>
  <li>
    <p> <strong>Clean Sale</strong>: You represent and confirm  that you shall be the sole and exclusive legal owner of all items of any  description that you propose to offer for sale on the Website. You shall have  absolute right free of any encumbrance, lien, hypothecation, mortgage, charge,  and adequate title and authority to deal in and offer for sale such items as  may be listed by you on the Website. </p>
    <p>If it comes to your knowledge that any Transaction or attempted  Transaction relating to any item listed on the Website is violative of this  clause or this User Agreement or applicable laws, you shall take all steps to  inform the Company of the same forthwith. </p>
  </li>
  <li> <strong>Unfair Consumer Practice</strong>: You will not  engage in any unfair consumer practice or any such practices that are forbidden  under applicable laws, including but not restricted to the Consumer Protection  Act, 1986.</li>
  <li> <strong>Feedback</strong>: Buyers of items on the Website  are entitled to write reviews and rate the items as well as the seller on the  Website. As a seller, you accept that such reviews and rating may be adverse to  your business, economic and other interests including reputation. You hereby  relinquish any right you may have to take legal or any other action against  persons who have provided such reviews/ ratings or against the Company or the  Website for any loss of business, reputation or any other loss arising out of  such reviews or ratings provided by buyers and other Users in consideration of  being allowed to participate in the website for the purpose of selling your  items.</li>
  <li><strong>Non payment</strong>: The Company reserves the  right to issue a warning, temporarily /indefinitely suspend or terminate your  membership of the Website and refuse to provide you with access to the Website  in case of non-payment of Facility Charges or any other fees payable by you to  the Company whether for Kesaron Logistics services or otherwise. The  Company also reserves the right to take legal action in case of such  non-payment.</li>
  <li> <strong>International Trading</strong>: It will be solely  your responsibility to ensure that before listing an item for sale on the  Website, such item can be shipped outside India under applicable laws. If you  list any item that is in violation of the applicable laws, you will be liable  to make good any loss suffered or cost borne by the Website, the Company or  other Users who rely on such listing including reimbursement of any service  charges incurred towards the KesaronPay Facility or any other mode of payment or payments  made towards taxes or government charges or any levy in respect of such  item.  You shall also be responsible for  complying with all laws that may be applicable in the country where such item  is proposed to be Delivered. You are prohibited from selling any item to buyers  in countries with which trading is prohibited or under embargo (in general or  with respect to certain kind of goods) as imposed by the Government of India.</li>
  <li> <strong>Refusal to sell</strong>: Once any User confirms  a purchase in response to a listing made by you by making requisite payment  through Payment on Billing, the sale is considered complete and all property  and title in the listed item passes on to the buyer. You cannot refuse to sell  the item, or refuse to accept payment or fail to deliver the item after the  payment has been successfully made and the Transaction is confirmed. In case of  sale of item wherein the buyer has opted for Payment on Delivery as a payment  method, the sale is considered complete and all property and title in the  listed item passes on to the buyer only after payment of the Transaction Price  and upon Delivery.</li>
  <li> <strong>Pricing</strong>: The price of the item proposed  to be purchased shall include, if applicable, the shipping charges, insurance  charges and all other taxes, duties, costs, charges and expenses in respect  thereof. The shipping and handling charges included in the price of the item  must be reasonable and cannot be disproportionate to the cost of the item or  significantly above actual cost which maybe charged by a reputed and  competitive service provider. If the buyer makes payment in any currency other  than Indian Rupees, the cost of conversion/ exchange rate shall be borne by the  buyer.</li>
  <li> <strong>Buyer satisfaction</strong>: You hereby accept  the obligation to ensure high level of buyer satisfaction. If you receive more  than 10% negative reviews or feedback from Users who have bought items listed  by you, you will be considered to have failed to comply with this obligation.  In such case, the Company may at its sole discretion cancel your listing, place  limits on availability of services and facilities, suspend your account, demand  a security deposit for future listings or continue your listings, impose higher  fees and additional charges for permitting you to continue using the Website  for listing and selling items. You may communicate with a buyer after a  confirmed sale has taken place and directly resolve any complaint or dispute  that such buyer may have. </li>
  <li> <strong>Ending of Listing</strong>: You understand and  agree that the Company at its sole discretion may end any listing at any point  of time without any notice and also in case where any listing does not result  in a successful transaction within 30 days of listing. However, the Company may  choose not to remove any such listing and extend the period of listing for such  time as it thinks fit. A listing will naturally end if it results in a  confirmed Transaction.</li>
  <li><strong>Payment Confirmation</strong>: Subject to the  modes of payment chosen by the Seller, in case of payment by Payment on  Billing, upon successful receipt of the Transaction Price by the Company from  the Buyer within [3] days of booking the Transaction and completion of  verification of payment, the Company shall notify the buyer and the seller that  the Transaction Price has been received. In case of payment by Payment on  Delivery, the Company shall notify the buyer and seller that the buyer has  committed to pay the Transaction Price by Payment on Delivery.</li>
  <li>
    <p><strong>Rules for Dispatch</strong>: The seller (other  than a seller availing the 'courier' services under Kesaron Logistics) is  required to Dispatch the items for every Transaction to the Buyer within [3]  days from the Payment Confirmation or within such timelines as may be agreed  upon between the buyer and seller through the Website to ensure that the items  are Delivered within timely manner. You should Dispatch the item only after  receiving the Payment Confirmation from the Company.</p>
    <ul>
    <li>You must use reputed postal/  courier service provider with good track record which provide tracking facility  for shipped items.</li>
    <li> You shall Dispatch the items  using only a delivery channel which provides appropriate &lsquo;proof of dispatch&rsquo;  &amp; &lsquo;proof of delivery&rsquo; documentation. Such proof of dispatch and proof of  delivery documentation (<strong>PODs</strong>)  relating to the Dispatch and Delivery should be maintained by you for period of  [9] months from the date of the Dispatch. The PODs should be furnished to the  Company on demand within the timeframe as notified from time to time. </li>
    <li> You agree that the Dispatch  Details shall be true, correct and duly authorized and shall not be misleading,  fraudulent, false, unauthorized or otherwise illegal and shall not contain any  misrepresentation of facts. </li>
    <li> You shall send an invoice  addressed to the Buyer for the Transaction Price together with the item at the  time of Dispatch.</li>
    <li> If the Seller fails to provide  the Dispatch Details as prescribed below, in addition to the cancellation of  the transaction, such failure may lead to suspension and/or termination of  Seller&rsquo;s KesaronPay Registration and/or any consequent actions as specified in  the User Agreement. </li>
    </ul>
    <p> <strong>Dispatch Details:</strong> The Seller shall provide the Dispatch Details on the Website within [7] days from the Payment Confirmation or within such timelines as may be agreed upon between the buyer and seller on the Website. If the Seller fails to enter the Dispatch Details in the Website within such prescribed time, the Company may in its sole discretion cancel the Transaction and refund the Transaction Price (if paid) to the Buyer. In case of Delivery outside India (in which case only electronic payment shall be acceptable), the Dispatch Details have to be entered in the KesaronPay Facility within 10 days of Payment Confirmation.</p>
    <p> In case of Transactions wherein the buyer has opted for Payment on Delivery payment method or the seller has availed of the 'courier' services under Kesaron Logistics, the Logistics Partner would collect the item to be shipped from the Seller and the Company would be responsible for providing the Dispatch Details on the Website. </p>
    <p> If the seller has opted for the 'courier' services under Kesaron Logistics the seller will be bound by the terms of the Policy for Kesaron Logistics (incorporated herein by reference) and the Logistics Partner and/or the Company shall be responsible for abiding by the terms and obligations of this provision including but limited to providing the Dispatch Details. </p>
  </li>
  <li>
    <p><strong>Delivery:</strong> The time within which the seller or the Company (if the seller is availing Kesaron Logistics services) is required to ensure Delivery of the items to the Buyer shall be calculated from the time the Seller enters the Dispatch Details on the Website i.e. within 10 days from entering the Dispatch Details for delivery within India and within 21 days from entering the Dispatch Details for delivery outside India or such other timeline as may have been agreed upon between the Buyer and Seller on the Website. </p>
    <p> In case of Payment on Delivery Transactions, the Logistics Partner will Deliver the items and collect the Transaction Price and other charges (if any) within the stipulated time.    It is the sole responsibility of the seller to ensure that the goods shipped are received by the buyer are in good condition and not damaged for any reason whatsoever, irrespective of whether the delivery is made by the Logistics Partner or seller has availed the services of Kesaron Logistics. </p>
  </li>
  <li>
    <p><strong>Remittance to Sellers:</strong> Seller agrees that the Transaction Price paid by a Buyer will be remitted to Seller&rsquo;s Bank Account contingent upon the following events: </p>
    <ul>
    <li>Buyer confirming the Delivery of items in the Transaction, or</li>
    <li>Buyer not taking any action on the Website to confirm Delivery or non- receipt of item within [5] days of expiry of the prescribed Delivery time despite the confirmation of Dispatch of item by Seller to the Buyer, or</li>
    <li>Buyer does not raise a refund claim within [5] days of expiry of the prescribed Delivery time or if such claim has been raised by the Buyer, the same is rejected by the Company on account of any breach of the User Agreement and the rules and polices made thereunder and/or applicable law, or </li>
    </ul>
    <p>All remittances to Sellers in respect of Payment on Delivery Transactions shall be made through cheque/ demand draft or online bank transfer to Seller's Bank Account.    In cases where the Payment on Delivery option is selected, remittance of the Transaction Price paid by the Buyer will be made within [21] days of Delivery and only after the payments received from the Logistics Partner are reconciled with the Website/ Company. </p>
    <p> The Company reserves the right to keep on hold the remittance to the Seller for purposes of safety of the KesaronPay Facility and/or Users. In such case, the Seller will be intimated and required to complete additional check and verification and the Company may contact the Seller for verification of or additional information, details, data and documents. The Company reserves the right to refund the Transaction Price that has been kept on hold to the Buyer, if such requisite information, details, data and documents are not provided within the stipulated time, or the same is false, misleading, incorrect or incomplete. </p>
    <p>Remittances to the Seller for their successful Transactions under the KesaronPay Facility would be in accordance with the provisions contained herein and applicable laws in India, particularly the directions issued by the Reserve Bank of India from time to time for opening and operation of accounts and settlement of payments for electronic payment transactions involving intermediaries dated 24 November 2009.</p>
  </li>
  <li>
    <h2>Warranties and Undertakings</h2>
    <p>Seller warrants and undertakes that: </p>
    <ul>
    <li>All sales of items listed on the Website are on principal to principal basis and bipartite contracts between seller and buyer. Seller shall be solely responsible for the condition, description, trademark, Delivery, warranty, payment, all applicable government taxes and duties, legality, legal title in relation to the items and other terms and conditions of the Transaction. The Company by providing facilities on the Website and/or Kesaron Logistics services does not in any way becomes a party to the contract for the sale of the item.</li>
    <li>Seller shall maintain proper proof of delivery (POD) of the items sent to the Buyer. PODs should be furnished to the Company on demand within the prescribed time period. Failure to furnish proof of delivery will be tantamount to the product not sent by the seller and the buyer will be entitled to refund. </li>
    <li>In the event that:
    <ul>
      <li>the Seller fails to Deliver within the time prescribed; or </li>
      <li>the Seller sells or Delivers any illegal, prohibited or counterfeit items; or </li>
      <li>the description of the items  listed do not match the actual condition of the items or the items are defective or damaged on Delivery; or </li>
      <li>there is any dispute between Seller and the Buyer relating to the Transaction, or </li>
      <li>the use of a Valid Card or Valid Bank Account by a Buyer while paying Transaction Price was unauthorized or was a result of fraud or hacking of bank account password; or </li>
      <li>the Buyer claims a refund of or charges back the Transaction Price,</li>
    </ul>
    <p>the Company has the right to take appropriate legal action including right to set off from subsequent remittances to seller until such amount is fully recovered. In case the subsequent balances are not enough for recovery, within 7 days of receipt of a notice to that effect from the Company, the Seller shall pay the shortfall to the Company. In case the Company is not able to recover the shortfall, within the given time, it reserves the rights to take appropriate legal actions against Seller. </p>
    </li>
    <li>Seller further unconditionally indemnifies and hold harmless the Company, its affiliates and its third party service providers and their respective directors, officers and employees against any actions, proceedings, costs, awards, claims and damages however incurred by or arising against them as a result of any act or omission on Seller&rsquo;s part while entering into and performing the contract with the Buyers or using the KesaronPay Facility. </li>
    <li>In the event that any Transaction Price remitted to Seller is uncollectible and a claim is raised on the Company in respect thereof, the same shall be Seller&rsquo;s financial responsibility and the Company shall have the right to recover any such amounts from the Seller in the manner provided herein above without any hindrance/ protest.</li>
    <li>Seller shall abide by and complete all Transactions in accordance with the description and conditions mentioned in such Transaction and the provisions of the User Agreement and the rules and policies made thereunder. </li>
    </ul>
  </li>
  <li>
    <p><strong>Seller verification and refund to Buyers: </strong>The Seller authorises the Company to perform certain checks before  remitting the Transaction Price to Seller&rsquo;s Bank Account to ensure the safety  of the Transaction, Website and to mitigate any payment risks. As part of  performing such checks, the Company will also have the right to hold the  remittance to the Seller&rsquo;s Valid Bank Account and require Seller to furnish  certain documents for verification purposes. The Company also reserves the  right to refund the Transaction Price back to the Buyer which the Company has  withheld or continue holding the periodic payments (including all future  payments) in any of the following conditions:</p>
    <ul>
    <li>If the Seller does not provide  the requisite verification documents within the prescribed time frame  communicated by the Company or as provided in the rules and policies of the  Website; or</li>
    <li> If the verification documents  submitted are invalid, tampered or forged; or </li>
    <li> If the verification documents  suggest that the Dispatch has been done to an address which is different from  the shipping address provided by the Buyer; or </li>
    <li> If the Seller has not  Dispatched the items using a recognized dispatch channel but used any other  means; or</li>
    <li> If Seller has provided  incorrect or invalid Dispatch Details or has not Delivered the item to Buyer;  or </li>
    <li> If the Seller has listed an  Item which violates the User Agreement or the rules and polices made thereunder;  or</li>
    <li> If the Seller has Dispatched an  item different from the description mentioned on the Transaction, or </li>
    <li> The Company is instructed by  any law enforcement agency or government or statutory authority to deny or  decline or withhold such remittance. </li>
    </ul>
    <p> In  all the above cases the Company will not be held liable for any loss incurred  by the Seller arising out of such refund.</p>
  </li>
  <li><strong>Chargeback</strong><br>
    A chargeback occurs  when the card-holder disputes a charge on his credit / debit card statement  with his card-Issuing Bank. On receiving such complaint from the card-holder,  the card Issuing Bank credits the card holder and recovers the amount from the  Company. The Company is entitled to deduct such amount from any amount payable  to the Seller by the Company. If no such amount is payable the Company may  demand such amount to be paid forthwith by the Seller. The Seller will notified  of the recovery, if any, through an email and may receive an acknowledgement of  payment if requested. If the payment gateway facility provider, bank or the  service providers of the Company charge the Company with any penalty or fee or  charge for such chargeback in respect of the Transaction which the Company is  required to pay, the Seller will be liable to pay such penalty or fee to the  Company, and the same may be recovered in the manner aforesaid.</li>
  <li><strong>Data Retention</strong><br>
    The  Company will retain personal information in accordance with the privacy polices  posted on the Website and applicable laws. </li>
  </ul>
  <h3 align="center">ANNEX 1</h3>
  <h2 align="center">LIST OF RESTRICTED ITEMS</h2>
  <ul>
  <li>Alcohol which includes alcohol or alcoholic beverages such  as beer, liquor, wine or champagne</li>
  <li>Adult goods and services which  includes pornography and other sexually suggestive materials (including  literature, imagery and other media); escort or prostitution services; Website  access and/or website memberships of pornography or illegal sites </li>
  <li> Body parts which includes  organs or other body parts </li>
  <li> Bulk marketing tools which  includes email lists, software or other producers enabling unsolicited email  messages (spam) </li>
  <li> Cable descramblers and black boxes  which includes devices intended to obtain cable and satellite signals for free </li>
  <li> Child pornography which  includes pornographic materials involving minors </li>
  <li> Copyright unlocking devices  which include Mod chips or other devices designed to circumvent copyright  protection </li>
  <li> Copyrighted media which  includes unauthorized copies of books, music, movies and other licensed or  protected materials </li>
  <li> Copyrighted software which  includes unauthorized copies of software, video games and other licensed or  protected materials, including OEM or bundled software </li>
  <li> Counterfeit and unauthorized  goods which includes replicas or imitations of designer goods; items without a  celebrity endorsement that would normally require such an association; fake  autographs, counterfeit stamps, and other potentially unauthorized goods </li>
  <li> Drugs and drug paraphernalia  which includes illegal drugs and drug accessories, including herbal drugs like  salvia and magic mushrooms </li>
  <li> Drug test circumvention aids  which includes drug cleansing shakes, urine test additives, and related items </li>
  <li> Endangered species which  includes plants, animals or other organisms (including product derivates) in  danger of extinction </li>
  <li> Gaming/Gambling which includes  lottery tickets sports bets, memberships/enrollment/  online gambling sites, and related content </li>
  <li> Government IDs or documents  which includes fake IDs, passports, diplomas and noble titles </li>
  <li> Hacking and cracking material  which includes manuals, how-to guides, information, or equipment enabling  illegal access to software's, servers websites, or other protected property </li>
  <li> Illegal goods which includes  materials, products, or information promoting illegal goods or enabling illegal  acts </li>
  <li> Miracle cures which includes  unsubstantiated cures, remedies or other items marketed as quick health fixes </li>
  <li> Offensive goods which includes  literature, products or other material that: </li>
  <li> Defame or slander any person or  groups of people based on race, ethnicity, national origin, religion, sex, or  other factors </li>
  <li> Encourage or incite violent  acts </li>
  <li> Promote intolerance or hatred </li>
  <li> Offensive goods, crime which  includes crime scene photos or items, such as personal belongings, associated  with criminals </li>
  <li> Prescription dugs or herbal  drugs or any kind of online pharmacies which includes drug or any other  products which requires a prescription by a licensed medical practioner. </li>
  <li> Pyrotechnic devices,  combustibles, corrosives and hazardous materials which includes explosives,  fireworks and related goods; toxic, flammable and radioactive materials and  substances </li>
  <li> Regulated goods which includes  air bags; batteries containing mercury; Freon or other similar  substances/refrigerants; chemical/industrial solvents; government uniforms; car  titles; license plates; police badges and law enforcement equipment;  lock-picking devices; pesticides; postage meters; recalled items slot machines;  surveillance equipment; goods regulated by government or other agency  specifications </li>
  <li> Securities which includes  stocks, bonds, or related financial products </li>
  <li> Tobacco and cigarettes which  includes cigarettes, cigars, chewing tobacco, and related products </li>
  <li> Traffic devices which includes  radar detectors/jammers, license plate covers, traffic signal changers,  and related products </li>
  <li> Weapons which includes  firearms, ammunition, knives, brass knuckles, gun parts and other armaments </li>
  <li> Wholesale currency which  includes discounted currencies or currency exchanges </li>
  <li> Live animals or  hides/skin/teeth, nails and other parts etc. of animals </li>
  <li> Multi level marketing  collection fees </li>
  <li> Matrix sites or sites using a  matrix scheme approach </li>
  <li> Work-at-home approach and/or  work-at-home information </li>
  <li> Drop-shipped merchandise </li>
  <li> Any product or service which is  not in compliance with all applicable laws and regulations whether federal,  state, local or international, including the laws of India. </li>
  <li> The merchant providing services  that have the potential of citing the Payment Gateway Facilitators in a poor  light and/or that may be prone to &ldquo;Buy &amp; Deny&rdquo; attitude of the cardholders  when billed (e.g. adult material/mature content/escort services/friend finders)  and thus leading to chargeback and fraud losses </li>
  <li> Business or websites that  operate within the scope of law which are not absolutely clear or are ambiguous  in nature (Web-based telephony, websites supplying medicines or controlled  substances, websites that promise online match making, etc) </li>
  <li> Businesses out rightly banned  by law (e.g. betting &amp; gambling/publications and content that is likely to  be interpreted by authorities as leading to moral turpitude or decadence or  incite caste/communal tensions, lotteries/ sweepstakes&amp; games of chance) </li>
  <li> The merchant who deal in  intangible goods/services (e.g. software download/health/beauty products), and  business involving pyramid marketing schemes or get-rick-quick schemes. Any  other product or service which in the sole opinion of the EBS or the Payment  Gateway facilitators, is detrimental to the image and interests of either of  them/ both of them, as communicated by either of them/both of them to the  merchant from time to time. This shall be without prejudice to any other terms  and conditions mentioned in this Agreement. </li>
  <li> Bulk marketing tools which  includes emails, lists, software or other products enabling unsolicited email  messages (spam) </li>
  <li> Web-based  telephony/SMS/Text/Facsimile services or Calling cards. Bandwidth or data  transfer/ allied services. Voice process/knowledge process services </li>
  <li> Mailing lists </li>
  </ul>
  <h3 align="center">ANNEX 2</h3>
  <h2 align="center">COMMISSION STRUCTURE</h2>
  <ul>
  <li>
    <p>We charge 25% Commission + Applicable Service Tax + Logistics Charges. The commission is calculated on the sale price of the product of the Seller. Any direct or indirect discounts given by the Company will not be considered in the sale price. Shipping, packaging and handling is managed by Seller. For Cash on Delivery, Kesaron appointed Logistics service provider will be used.</p>
  </li>
  </ul>
  </div>
</div>

                    </div><!-- End .row -->
                </div>